# Generated by Django 4.1.1 on 2022-09-24 03:50

from django.db import migrations, models
import uuid


class Migration(migrations.Migration):

    dependencies = [
        ('mymenu', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='admin',
            name='uuid',
            field=models.UUIDField(db_index=True, default=uuid.uuid4, editable=False, unique=True),
        ),
    ]
